### ISSUE TITLE
Question: Are the experiments run with episodic lives?

### ISSUE THREAD

**Issue by NikEyX** [ray-project/rl-experiments#1]
Looking at the 1h wall-time results for the atari games on ApeX:
```
BeamRider | 4873 | ~1000 | ~300
Breakout | 77 | ~10 | ~1
QBert | 4083 | ~500 | ~150
SpaceInvaders | 646 | ~300 | ~160
```
Are these numbers based on playing out the entire game? E.g. do the numbers for BreakOut indicate the total score over 5 lives? Or are these numbers based on the episodic lives wrapper, where each episodes terminates when you lose a life? 

What about the training? Is that using episodic lives?

**Comment by richardliaw** [comment]
cc @ericl

**Comment by ericl** [comment]
Scored over all lives. Note that this is the standard reporting metric for
Atari.

Training is per-life.

Eric

**Comment by NikEyX** [comment]
Great, thanks for the prompt reply!
